/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumo_combustivel;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    //Teste default da aplicacao
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
